//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18033.
// 
#pragma warning disable 1591

namespace FACliente.localhostPlano {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLastMsgErrorOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarPlanoTreinamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarPlanoTreinamentoExOperationCompleted;
        
        private System.Threading.SendOrPostCallback salvarPlanoTreinamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback excluirPlanoTreinamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback pegarPlanoTreinamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback pegarPlanoTreinamentoExOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarClientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarObjetivosOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarExerciciosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::FACliente.Properties.Settings.Default.FACliente_localhostPlano_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event getLastMsgErrorCompletedEventHandler getLastMsgErrorCompleted;
        
        /// <remarks/>
        public event consultarPlanoTreinamentoCompletedEventHandler consultarPlanoTreinamentoCompleted;
        
        /// <remarks/>
        public event consultarPlanoTreinamentoExCompletedEventHandler consultarPlanoTreinamentoExCompleted;
        
        /// <remarks/>
        public event salvarPlanoTreinamentoCompletedEventHandler salvarPlanoTreinamentoCompleted;
        
        /// <remarks/>
        public event excluirPlanoTreinamentoCompletedEventHandler excluirPlanoTreinamentoCompleted;
        
        /// <remarks/>
        public event pegarPlanoTreinamentoCompletedEventHandler pegarPlanoTreinamentoCompleted;
        
        /// <remarks/>
        public event pegarPlanoTreinamentoExCompletedEventHandler pegarPlanoTreinamentoExCompleted;
        
        /// <remarks/>
        public event listarClientesCompletedEventHandler listarClientesCompleted;
        
        /// <remarks/>
        public event listarObjetivosCompletedEventHandler listarObjetivosCompleted;
        
        /// <remarks/>
        public event listarExerciciosCompletedEventHandler listarExerciciosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLastMsgError", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getLastMsgError() {
            object[] results = this.Invoke("getLastMsgError", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getLastMsgErrorAsync() {
            this.getLastMsgErrorAsync(null);
        }
        
        /// <remarks/>
        public void getLastMsgErrorAsync(object userState) {
            if ((this.getLastMsgErrorOperationCompleted == null)) {
                this.getLastMsgErrorOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLastMsgErrorOperationCompleted);
            }
            this.InvokeAsync("getLastMsgError", new object[0], this.getLastMsgErrorOperationCompleted, userState);
        }
        
        private void OngetLastMsgErrorOperationCompleted(object arg) {
            if ((this.getLastMsgErrorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLastMsgErrorCompleted(this, new getLastMsgErrorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultarPlanoTreinamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PlanoTreinamento[] consultarPlanoTreinamento(PlanoTreinamento obj, System.DateTime dataFinal) {
            object[] results = this.Invoke("consultarPlanoTreinamento", new object[] {
                        obj,
                        dataFinal});
            return ((PlanoTreinamento[])(results[0]));
        }
        
        /// <remarks/>
        public void consultarPlanoTreinamentoAsync(PlanoTreinamento obj, System.DateTime dataFinal) {
            this.consultarPlanoTreinamentoAsync(obj, dataFinal, null);
        }
        
        /// <remarks/>
        public void consultarPlanoTreinamentoAsync(PlanoTreinamento obj, System.DateTime dataFinal, object userState) {
            if ((this.consultarPlanoTreinamentoOperationCompleted == null)) {
                this.consultarPlanoTreinamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarPlanoTreinamentoOperationCompleted);
            }
            this.InvokeAsync("consultarPlanoTreinamento", new object[] {
                        obj,
                        dataFinal}, this.consultarPlanoTreinamentoOperationCompleted, userState);
        }
        
        private void OnconsultarPlanoTreinamentoOperationCompleted(object arg) {
            if ((this.consultarPlanoTreinamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarPlanoTreinamentoCompleted(this, new consultarPlanoTreinamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultarPlanoTreinamentoEx", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PlanoTreinamento[] consultarPlanoTreinamentoEx(PlanoTreinamento obj, System.DateTime dataFinal, int toStringBehavior) {
            object[] results = this.Invoke("consultarPlanoTreinamentoEx", new object[] {
                        obj,
                        dataFinal,
                        toStringBehavior});
            return ((PlanoTreinamento[])(results[0]));
        }
        
        /// <remarks/>
        public void consultarPlanoTreinamentoExAsync(PlanoTreinamento obj, System.DateTime dataFinal, int toStringBehavior) {
            this.consultarPlanoTreinamentoExAsync(obj, dataFinal, toStringBehavior, null);
        }
        
        /// <remarks/>
        public void consultarPlanoTreinamentoExAsync(PlanoTreinamento obj, System.DateTime dataFinal, int toStringBehavior, object userState) {
            if ((this.consultarPlanoTreinamentoExOperationCompleted == null)) {
                this.consultarPlanoTreinamentoExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarPlanoTreinamentoExOperationCompleted);
            }
            this.InvokeAsync("consultarPlanoTreinamentoEx", new object[] {
                        obj,
                        dataFinal,
                        toStringBehavior}, this.consultarPlanoTreinamentoExOperationCompleted, userState);
        }
        
        private void OnconsultarPlanoTreinamentoExOperationCompleted(object arg) {
            if ((this.consultarPlanoTreinamentoExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarPlanoTreinamentoExCompleted(this, new consultarPlanoTreinamentoExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/salvarPlanoTreinamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void salvarPlanoTreinamento(PlanoTreinamento obj) {
            this.Invoke("salvarPlanoTreinamento", new object[] {
                        obj});
        }
        
        /// <remarks/>
        public void salvarPlanoTreinamentoAsync(PlanoTreinamento obj) {
            this.salvarPlanoTreinamentoAsync(obj, null);
        }
        
        /// <remarks/>
        public void salvarPlanoTreinamentoAsync(PlanoTreinamento obj, object userState) {
            if ((this.salvarPlanoTreinamentoOperationCompleted == null)) {
                this.salvarPlanoTreinamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsalvarPlanoTreinamentoOperationCompleted);
            }
            this.InvokeAsync("salvarPlanoTreinamento", new object[] {
                        obj}, this.salvarPlanoTreinamentoOperationCompleted, userState);
        }
        
        private void OnsalvarPlanoTreinamentoOperationCompleted(object arg) {
            if ((this.salvarPlanoTreinamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.salvarPlanoTreinamentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/excluirPlanoTreinamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void excluirPlanoTreinamento(PlanoTreinamento obj) {
            this.Invoke("excluirPlanoTreinamento", new object[] {
                        obj});
        }
        
        /// <remarks/>
        public void excluirPlanoTreinamentoAsync(PlanoTreinamento obj) {
            this.excluirPlanoTreinamentoAsync(obj, null);
        }
        
        /// <remarks/>
        public void excluirPlanoTreinamentoAsync(PlanoTreinamento obj, object userState) {
            if ((this.excluirPlanoTreinamentoOperationCompleted == null)) {
                this.excluirPlanoTreinamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexcluirPlanoTreinamentoOperationCompleted);
            }
            this.InvokeAsync("excluirPlanoTreinamento", new object[] {
                        obj}, this.excluirPlanoTreinamentoOperationCompleted, userState);
        }
        
        private void OnexcluirPlanoTreinamentoOperationCompleted(object arg) {
            if ((this.excluirPlanoTreinamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.excluirPlanoTreinamentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pegarPlanoTreinamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PlanoTreinamento pegarPlanoTreinamento(int codigo) {
            object[] results = this.Invoke("pegarPlanoTreinamento", new object[] {
                        codigo});
            return ((PlanoTreinamento)(results[0]));
        }
        
        /// <remarks/>
        public void pegarPlanoTreinamentoAsync(int codigo) {
            this.pegarPlanoTreinamentoAsync(codigo, null);
        }
        
        /// <remarks/>
        public void pegarPlanoTreinamentoAsync(int codigo, object userState) {
            if ((this.pegarPlanoTreinamentoOperationCompleted == null)) {
                this.pegarPlanoTreinamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpegarPlanoTreinamentoOperationCompleted);
            }
            this.InvokeAsync("pegarPlanoTreinamento", new object[] {
                        codigo}, this.pegarPlanoTreinamentoOperationCompleted, userState);
        }
        
        private void OnpegarPlanoTreinamentoOperationCompleted(object arg) {
            if ((this.pegarPlanoTreinamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pegarPlanoTreinamentoCompleted(this, new pegarPlanoTreinamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pegarPlanoTreinamentoEx", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PlanoTreinamento pegarPlanoTreinamentoEx(int codigo, int toStringBehavior) {
            object[] results = this.Invoke("pegarPlanoTreinamentoEx", new object[] {
                        codigo,
                        toStringBehavior});
            return ((PlanoTreinamento)(results[0]));
        }
        
        /// <remarks/>
        public void pegarPlanoTreinamentoExAsync(int codigo, int toStringBehavior) {
            this.pegarPlanoTreinamentoExAsync(codigo, toStringBehavior, null);
        }
        
        /// <remarks/>
        public void pegarPlanoTreinamentoExAsync(int codigo, int toStringBehavior, object userState) {
            if ((this.pegarPlanoTreinamentoExOperationCompleted == null)) {
                this.pegarPlanoTreinamentoExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpegarPlanoTreinamentoExOperationCompleted);
            }
            this.InvokeAsync("pegarPlanoTreinamentoEx", new object[] {
                        codigo,
                        toStringBehavior}, this.pegarPlanoTreinamentoExOperationCompleted, userState);
        }
        
        private void OnpegarPlanoTreinamentoExOperationCompleted(object arg) {
            if ((this.pegarPlanoTreinamentoExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pegarPlanoTreinamentoExCompleted(this, new pegarPlanoTreinamentoExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarClientes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente[] listarClientes() {
            object[] results = this.Invoke("listarClientes", new object[0]);
            return ((Cliente[])(results[0]));
        }
        
        /// <remarks/>
        public void listarClientesAsync() {
            this.listarClientesAsync(null);
        }
        
        /// <remarks/>
        public void listarClientesAsync(object userState) {
            if ((this.listarClientesOperationCompleted == null)) {
                this.listarClientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarClientesOperationCompleted);
            }
            this.InvokeAsync("listarClientes", new object[0], this.listarClientesOperationCompleted, userState);
        }
        
        private void OnlistarClientesOperationCompleted(object arg) {
            if ((this.listarClientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarClientesCompleted(this, new listarClientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarObjetivos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Objetivo[] listarObjetivos() {
            object[] results = this.Invoke("listarObjetivos", new object[0]);
            return ((Objetivo[])(results[0]));
        }
        
        /// <remarks/>
        public void listarObjetivosAsync() {
            this.listarObjetivosAsync(null);
        }
        
        /// <remarks/>
        public void listarObjetivosAsync(object userState) {
            if ((this.listarObjetivosOperationCompleted == null)) {
                this.listarObjetivosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarObjetivosOperationCompleted);
            }
            this.InvokeAsync("listarObjetivos", new object[0], this.listarObjetivosOperationCompleted, userState);
        }
        
        private void OnlistarObjetivosOperationCompleted(object arg) {
            if ((this.listarObjetivosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarObjetivosCompleted(this, new listarObjetivosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarExercicios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Exercicio[] listarExercicios() {
            object[] results = this.Invoke("listarExercicios", new object[0]);
            return ((Exercicio[])(results[0]));
        }
        
        /// <remarks/>
        public void listarExerciciosAsync() {
            this.listarExerciciosAsync(null);
        }
        
        /// <remarks/>
        public void listarExerciciosAsync(object userState) {
            if ((this.listarExerciciosOperationCompleted == null)) {
                this.listarExerciciosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarExerciciosOperationCompleted);
            }
            this.InvokeAsync("listarExercicios", new object[0], this.listarExerciciosOperationCompleted, userState);
        }
        
        private void OnlistarExerciciosOperationCompleted(object arg) {
            if ((this.listarExerciciosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarExerciciosCompleted(this, new listarExerciciosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PlanoTreinamento {
        
        private int numplanoField;
        
        private System.DateTime dataField;
        
        private Objetivo objetivoDoPlanoField;
        
        private Cliente clienteDoPlanoField;
        
        private ExercicioDoPlano[] exerciciosField;
        
        /// <remarks/>
        public int Numplano {
            get {
                return this.numplanoField;
            }
            set {
                this.numplanoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public Objetivo ObjetivoDoPlano {
            get {
                return this.objetivoDoPlanoField;
            }
            set {
                this.objetivoDoPlanoField = value;
            }
        }
        
        /// <remarks/>
        public Cliente ClienteDoPlano {
            get {
                return this.clienteDoPlanoField;
            }
            set {
                this.clienteDoPlanoField = value;
            }
        }
        
        /// <remarks/>
        public ExercicioDoPlano[] Exercicios {
            get {
                return this.exerciciosField;
            }
            set {
                this.exerciciosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Objetivo {
        
        private int codigoField;
        
        private string descricaoField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Exercicio {
        
        private int codigoField;
        
        private string descricaoField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExercicioDoPlano {
        
        private int numPlanoField;
        
        private int seqField;
        
        private Exercicio exercicioField;
        
        private int seriesField;
        
        private int numRepeticoesField;
        
        private double pesoField;
        
        /// <remarks/>
        public int NumPlano {
            get {
                return this.numPlanoField;
            }
            set {
                this.numPlanoField = value;
            }
        }
        
        /// <remarks/>
        public int Seq {
            get {
                return this.seqField;
            }
            set {
                this.seqField = value;
            }
        }
        
        /// <remarks/>
        public Exercicio Exercicio {
            get {
                return this.exercicioField;
            }
            set {
                this.exercicioField = value;
            }
        }
        
        /// <remarks/>
        public int Series {
            get {
                return this.seriesField;
            }
            set {
                this.seriesField = value;
            }
        }
        
        /// <remarks/>
        public int NumRepeticoes {
            get {
                return this.numRepeticoesField;
            }
            set {
                this.numRepeticoesField = value;
            }
        }
        
        /// <remarks/>
        public double Peso {
            get {
                return this.pesoField;
            }
            set {
                this.pesoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cliente {
        
        private int codigoField;
        
        private string nomeField;
        
        private string cpfField;
        
        private string rgField;
        
        private System.DateTime dataNascField;
        
        private string logradouroField;
        
        private string numLogField;
        
        private string complementoField;
        
        private string bairroField;
        
        private string cidadeField;
        
        private string ufField;
        
        private string cepField;
        
        private string estCivilField;
        
        private string sexoField;
        
        private string telefoneField;
        
        private string celularField;
        
        private string emailField;
        
        private System.DateTime valExameMedicoField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        public string Rg {
            get {
                return this.rgField;
            }
            set {
                this.rgField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataNasc {
            get {
                return this.dataNascField;
            }
            set {
                this.dataNascField = value;
            }
        }
        
        /// <remarks/>
        public string Logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        public string NumLog {
            get {
                return this.numLogField;
            }
            set {
                this.numLogField = value;
            }
        }
        
        /// <remarks/>
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        public string Cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        public string EstCivil {
            get {
                return this.estCivilField;
            }
            set {
                this.estCivilField = value;
            }
        }
        
        /// <remarks/>
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        public string Celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ValExameMedico {
            get {
                return this.valExameMedicoField;
            }
            set {
                this.valExameMedicoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getLastMsgErrorCompletedEventHandler(object sender, getLastMsgErrorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLastMsgErrorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLastMsgErrorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void consultarPlanoTreinamentoCompletedEventHandler(object sender, consultarPlanoTreinamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarPlanoTreinamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarPlanoTreinamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PlanoTreinamento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PlanoTreinamento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void consultarPlanoTreinamentoExCompletedEventHandler(object sender, consultarPlanoTreinamentoExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarPlanoTreinamentoExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarPlanoTreinamentoExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PlanoTreinamento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PlanoTreinamento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void salvarPlanoTreinamentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void excluirPlanoTreinamentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void pegarPlanoTreinamentoCompletedEventHandler(object sender, pegarPlanoTreinamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pegarPlanoTreinamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pegarPlanoTreinamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PlanoTreinamento Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PlanoTreinamento)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void pegarPlanoTreinamentoExCompletedEventHandler(object sender, pegarPlanoTreinamentoExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pegarPlanoTreinamentoExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pegarPlanoTreinamentoExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PlanoTreinamento Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PlanoTreinamento)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void listarClientesCompletedEventHandler(object sender, listarClientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarClientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarClientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void listarObjetivosCompletedEventHandler(object sender, listarObjetivosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarObjetivosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarObjetivosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Objetivo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Objetivo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void listarExerciciosCompletedEventHandler(object sender, listarExerciciosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarExerciciosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarExerciciosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Exercicio[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Exercicio[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591