//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18034.
// 
#pragma warning disable 1591

namespace FACliente.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLastMsgErrorOperationCompleted;
        
        private System.Threading.SendOrPostCallback salvarTesteOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarExercicioOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarExercicioExOperationCompleted;
        
        private System.Threading.SendOrPostCallback salvarExercicioOperationCompleted;
        
        private System.Threading.SendOrPostCallback excluirExercicioOperationCompleted;
        
        private System.Threading.SendOrPostCallback pegarExercicioOperationCompleted;
        
        private System.Threading.SendOrPostCallback pegarExercicioExOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarObjetivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarObjetivoExOperationCompleted;
        
        private System.Threading.SendOrPostCallback salvarObjetivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback excluirObjetivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback pegarObjetivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback pegarObjetivoExOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarClienteExOperationCompleted;
        
        private System.Threading.SendOrPostCallback salvarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback excluirClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback pegarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback pegarClienteExOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::FACliente.Properties.Settings.Default.FACliente_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event getLastMsgErrorCompletedEventHandler getLastMsgErrorCompleted;
        
        /// <remarks/>
        public event salvarTesteCompletedEventHandler salvarTesteCompleted;
        
        /// <remarks/>
        public event consultarExercicioCompletedEventHandler consultarExercicioCompleted;
        
        /// <remarks/>
        public event consultarExercicioExCompletedEventHandler consultarExercicioExCompleted;
        
        /// <remarks/>
        public event salvarExercicioCompletedEventHandler salvarExercicioCompleted;
        
        /// <remarks/>
        public event excluirExercicioCompletedEventHandler excluirExercicioCompleted;
        
        /// <remarks/>
        public event pegarExercicioCompletedEventHandler pegarExercicioCompleted;
        
        /// <remarks/>
        public event pegarExercicioExCompletedEventHandler pegarExercicioExCompleted;
        
        /// <remarks/>
        public event consultarObjetivoCompletedEventHandler consultarObjetivoCompleted;
        
        /// <remarks/>
        public event consultarObjetivoExCompletedEventHandler consultarObjetivoExCompleted;
        
        /// <remarks/>
        public event salvarObjetivoCompletedEventHandler salvarObjetivoCompleted;
        
        /// <remarks/>
        public event excluirObjetivoCompletedEventHandler excluirObjetivoCompleted;
        
        /// <remarks/>
        public event pegarObjetivoCompletedEventHandler pegarObjetivoCompleted;
        
        /// <remarks/>
        public event pegarObjetivoExCompletedEventHandler pegarObjetivoExCompleted;
        
        /// <remarks/>
        public event consultarClienteCompletedEventHandler consultarClienteCompleted;
        
        /// <remarks/>
        public event consultarClienteExCompletedEventHandler consultarClienteExCompleted;
        
        /// <remarks/>
        public event salvarClienteCompletedEventHandler salvarClienteCompleted;
        
        /// <remarks/>
        public event excluirClienteCompletedEventHandler excluirClienteCompleted;
        
        /// <remarks/>
        public event pegarClienteCompletedEventHandler pegarClienteCompleted;
        
        /// <remarks/>
        public event pegarClienteExCompletedEventHandler pegarClienteExCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLastMsgError", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getLastMsgError() {
            object[] results = this.Invoke("getLastMsgError", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getLastMsgErrorAsync() {
            this.getLastMsgErrorAsync(null);
        }
        
        /// <remarks/>
        public void getLastMsgErrorAsync(object userState) {
            if ((this.getLastMsgErrorOperationCompleted == null)) {
                this.getLastMsgErrorOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLastMsgErrorOperationCompleted);
            }
            this.InvokeAsync("getLastMsgError", new object[0], this.getLastMsgErrorOperationCompleted, userState);
        }
        
        private void OngetLastMsgErrorOperationCompleted(object arg) {
            if ((this.getLastMsgErrorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLastMsgErrorCompleted(this, new getLastMsgErrorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/salvarTeste", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void salvarTeste() {
            this.Invoke("salvarTeste", new object[0]);
        }
        
        /// <remarks/>
        public void salvarTesteAsync() {
            this.salvarTesteAsync(null);
        }
        
        /// <remarks/>
        public void salvarTesteAsync(object userState) {
            if ((this.salvarTesteOperationCompleted == null)) {
                this.salvarTesteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsalvarTesteOperationCompleted);
            }
            this.InvokeAsync("salvarTeste", new object[0], this.salvarTesteOperationCompleted, userState);
        }
        
        private void OnsalvarTesteOperationCompleted(object arg) {
            if ((this.salvarTesteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.salvarTesteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultarExercicio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Exercicio[] consultarExercicio(Exercicio exer) {
            object[] results = this.Invoke("consultarExercicio", new object[] {
                        exer});
            return ((Exercicio[])(results[0]));
        }
        
        /// <remarks/>
        public void consultarExercicioAsync(Exercicio exer) {
            this.consultarExercicioAsync(exer, null);
        }
        
        /// <remarks/>
        public void consultarExercicioAsync(Exercicio exer, object userState) {
            if ((this.consultarExercicioOperationCompleted == null)) {
                this.consultarExercicioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarExercicioOperationCompleted);
            }
            this.InvokeAsync("consultarExercicio", new object[] {
                        exer}, this.consultarExercicioOperationCompleted, userState);
        }
        
        private void OnconsultarExercicioOperationCompleted(object arg) {
            if ((this.consultarExercicioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarExercicioCompleted(this, new consultarExercicioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultarExercicioEx", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Exercicio[] consultarExercicioEx(Exercicio exer, int toStringBehavior) {
            object[] results = this.Invoke("consultarExercicioEx", new object[] {
                        exer,
                        toStringBehavior});
            return ((Exercicio[])(results[0]));
        }
        
        /// <remarks/>
        public void consultarExercicioExAsync(Exercicio exer, int toStringBehavior) {
            this.consultarExercicioExAsync(exer, toStringBehavior, null);
        }
        
        /// <remarks/>
        public void consultarExercicioExAsync(Exercicio exer, int toStringBehavior, object userState) {
            if ((this.consultarExercicioExOperationCompleted == null)) {
                this.consultarExercicioExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarExercicioExOperationCompleted);
            }
            this.InvokeAsync("consultarExercicioEx", new object[] {
                        exer,
                        toStringBehavior}, this.consultarExercicioExOperationCompleted, userState);
        }
        
        private void OnconsultarExercicioExOperationCompleted(object arg) {
            if ((this.consultarExercicioExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarExercicioExCompleted(this, new consultarExercicioExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/salvarExercicio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void salvarExercicio(Exercicio exer) {
            this.Invoke("salvarExercicio", new object[] {
                        exer});
        }
        
        /// <remarks/>
        public void salvarExercicioAsync(Exercicio exer) {
            this.salvarExercicioAsync(exer, null);
        }
        
        /// <remarks/>
        public void salvarExercicioAsync(Exercicio exer, object userState) {
            if ((this.salvarExercicioOperationCompleted == null)) {
                this.salvarExercicioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsalvarExercicioOperationCompleted);
            }
            this.InvokeAsync("salvarExercicio", new object[] {
                        exer}, this.salvarExercicioOperationCompleted, userState);
        }
        
        private void OnsalvarExercicioOperationCompleted(object arg) {
            if ((this.salvarExercicioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.salvarExercicioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/excluirExercicio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void excluirExercicio(Exercicio exer) {
            this.Invoke("excluirExercicio", new object[] {
                        exer});
        }
        
        /// <remarks/>
        public void excluirExercicioAsync(Exercicio exer) {
            this.excluirExercicioAsync(exer, null);
        }
        
        /// <remarks/>
        public void excluirExercicioAsync(Exercicio exer, object userState) {
            if ((this.excluirExercicioOperationCompleted == null)) {
                this.excluirExercicioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexcluirExercicioOperationCompleted);
            }
            this.InvokeAsync("excluirExercicio", new object[] {
                        exer}, this.excluirExercicioOperationCompleted, userState);
        }
        
        private void OnexcluirExercicioOperationCompleted(object arg) {
            if ((this.excluirExercicioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.excluirExercicioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pegarExercicio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Exercicio pegarExercicio(int codigo) {
            object[] results = this.Invoke("pegarExercicio", new object[] {
                        codigo});
            return ((Exercicio)(results[0]));
        }
        
        /// <remarks/>
        public void pegarExercicioAsync(int codigo) {
            this.pegarExercicioAsync(codigo, null);
        }
        
        /// <remarks/>
        public void pegarExercicioAsync(int codigo, object userState) {
            if ((this.pegarExercicioOperationCompleted == null)) {
                this.pegarExercicioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpegarExercicioOperationCompleted);
            }
            this.InvokeAsync("pegarExercicio", new object[] {
                        codigo}, this.pegarExercicioOperationCompleted, userState);
        }
        
        private void OnpegarExercicioOperationCompleted(object arg) {
            if ((this.pegarExercicioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pegarExercicioCompleted(this, new pegarExercicioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pegarExercicioEx", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Exercicio pegarExercicioEx(int codigo, int toStringBehavior) {
            object[] results = this.Invoke("pegarExercicioEx", new object[] {
                        codigo,
                        toStringBehavior});
            return ((Exercicio)(results[0]));
        }
        
        /// <remarks/>
        public void pegarExercicioExAsync(int codigo, int toStringBehavior) {
            this.pegarExercicioExAsync(codigo, toStringBehavior, null);
        }
        
        /// <remarks/>
        public void pegarExercicioExAsync(int codigo, int toStringBehavior, object userState) {
            if ((this.pegarExercicioExOperationCompleted == null)) {
                this.pegarExercicioExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpegarExercicioExOperationCompleted);
            }
            this.InvokeAsync("pegarExercicioEx", new object[] {
                        codigo,
                        toStringBehavior}, this.pegarExercicioExOperationCompleted, userState);
        }
        
        private void OnpegarExercicioExOperationCompleted(object arg) {
            if ((this.pegarExercicioExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pegarExercicioExCompleted(this, new pegarExercicioExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultarObjetivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Objetivo[] consultarObjetivo(Objetivo obj) {
            object[] results = this.Invoke("consultarObjetivo", new object[] {
                        obj});
            return ((Objetivo[])(results[0]));
        }
        
        /// <remarks/>
        public void consultarObjetivoAsync(Objetivo obj) {
            this.consultarObjetivoAsync(obj, null);
        }
        
        /// <remarks/>
        public void consultarObjetivoAsync(Objetivo obj, object userState) {
            if ((this.consultarObjetivoOperationCompleted == null)) {
                this.consultarObjetivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarObjetivoOperationCompleted);
            }
            this.InvokeAsync("consultarObjetivo", new object[] {
                        obj}, this.consultarObjetivoOperationCompleted, userState);
        }
        
        private void OnconsultarObjetivoOperationCompleted(object arg) {
            if ((this.consultarObjetivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarObjetivoCompleted(this, new consultarObjetivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultarObjetivoEx", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Objetivo[] consultarObjetivoEx(Objetivo obj, int toStringBehavior) {
            object[] results = this.Invoke("consultarObjetivoEx", new object[] {
                        obj,
                        toStringBehavior});
            return ((Objetivo[])(results[0]));
        }
        
        /// <remarks/>
        public void consultarObjetivoExAsync(Objetivo obj, int toStringBehavior) {
            this.consultarObjetivoExAsync(obj, toStringBehavior, null);
        }
        
        /// <remarks/>
        public void consultarObjetivoExAsync(Objetivo obj, int toStringBehavior, object userState) {
            if ((this.consultarObjetivoExOperationCompleted == null)) {
                this.consultarObjetivoExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarObjetivoExOperationCompleted);
            }
            this.InvokeAsync("consultarObjetivoEx", new object[] {
                        obj,
                        toStringBehavior}, this.consultarObjetivoExOperationCompleted, userState);
        }
        
        private void OnconsultarObjetivoExOperationCompleted(object arg) {
            if ((this.consultarObjetivoExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarObjetivoExCompleted(this, new consultarObjetivoExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/salvarObjetivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void salvarObjetivo(Objetivo obj) {
            this.Invoke("salvarObjetivo", new object[] {
                        obj});
        }
        
        /// <remarks/>
        public void salvarObjetivoAsync(Objetivo obj) {
            this.salvarObjetivoAsync(obj, null);
        }
        
        /// <remarks/>
        public void salvarObjetivoAsync(Objetivo obj, object userState) {
            if ((this.salvarObjetivoOperationCompleted == null)) {
                this.salvarObjetivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsalvarObjetivoOperationCompleted);
            }
            this.InvokeAsync("salvarObjetivo", new object[] {
                        obj}, this.salvarObjetivoOperationCompleted, userState);
        }
        
        private void OnsalvarObjetivoOperationCompleted(object arg) {
            if ((this.salvarObjetivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.salvarObjetivoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/excluirObjetivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void excluirObjetivo(Objetivo obj) {
            this.Invoke("excluirObjetivo", new object[] {
                        obj});
        }
        
        /// <remarks/>
        public void excluirObjetivoAsync(Objetivo obj) {
            this.excluirObjetivoAsync(obj, null);
        }
        
        /// <remarks/>
        public void excluirObjetivoAsync(Objetivo obj, object userState) {
            if ((this.excluirObjetivoOperationCompleted == null)) {
                this.excluirObjetivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexcluirObjetivoOperationCompleted);
            }
            this.InvokeAsync("excluirObjetivo", new object[] {
                        obj}, this.excluirObjetivoOperationCompleted, userState);
        }
        
        private void OnexcluirObjetivoOperationCompleted(object arg) {
            if ((this.excluirObjetivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.excluirObjetivoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pegarObjetivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Objetivo pegarObjetivo(int codigo) {
            object[] results = this.Invoke("pegarObjetivo", new object[] {
                        codigo});
            return ((Objetivo)(results[0]));
        }
        
        /// <remarks/>
        public void pegarObjetivoAsync(int codigo) {
            this.pegarObjetivoAsync(codigo, null);
        }
        
        /// <remarks/>
        public void pegarObjetivoAsync(int codigo, object userState) {
            if ((this.pegarObjetivoOperationCompleted == null)) {
                this.pegarObjetivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpegarObjetivoOperationCompleted);
            }
            this.InvokeAsync("pegarObjetivo", new object[] {
                        codigo}, this.pegarObjetivoOperationCompleted, userState);
        }
        
        private void OnpegarObjetivoOperationCompleted(object arg) {
            if ((this.pegarObjetivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pegarObjetivoCompleted(this, new pegarObjetivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pegarObjetivoEx", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Objetivo pegarObjetivoEx(int codigo, int toStringBehavior) {
            object[] results = this.Invoke("pegarObjetivoEx", new object[] {
                        codigo,
                        toStringBehavior});
            return ((Objetivo)(results[0]));
        }
        
        /// <remarks/>
        public void pegarObjetivoExAsync(int codigo, int toStringBehavior) {
            this.pegarObjetivoExAsync(codigo, toStringBehavior, null);
        }
        
        /// <remarks/>
        public void pegarObjetivoExAsync(int codigo, int toStringBehavior, object userState) {
            if ((this.pegarObjetivoExOperationCompleted == null)) {
                this.pegarObjetivoExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpegarObjetivoExOperationCompleted);
            }
            this.InvokeAsync("pegarObjetivoEx", new object[] {
                        codigo,
                        toStringBehavior}, this.pegarObjetivoExOperationCompleted, userState);
        }
        
        private void OnpegarObjetivoExOperationCompleted(object arg) {
            if ((this.pegarObjetivoExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pegarObjetivoExCompleted(this, new pegarObjetivoExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente[] consultarCliente(Cliente obj) {
            object[] results = this.Invoke("consultarCliente", new object[] {
                        obj});
            return ((Cliente[])(results[0]));
        }
        
        /// <remarks/>
        public void consultarClienteAsync(Cliente obj) {
            this.consultarClienteAsync(obj, null);
        }
        
        /// <remarks/>
        public void consultarClienteAsync(Cliente obj, object userState) {
            if ((this.consultarClienteOperationCompleted == null)) {
                this.consultarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarClienteOperationCompleted);
            }
            this.InvokeAsync("consultarCliente", new object[] {
                        obj}, this.consultarClienteOperationCompleted, userState);
        }
        
        private void OnconsultarClienteOperationCompleted(object arg) {
            if ((this.consultarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarClienteCompleted(this, new consultarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultarClienteEx", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente[] consultarClienteEx(Cliente obj, int toStringBehavior) {
            object[] results = this.Invoke("consultarClienteEx", new object[] {
                        obj,
                        toStringBehavior});
            return ((Cliente[])(results[0]));
        }
        
        /// <remarks/>
        public void consultarClienteExAsync(Cliente obj, int toStringBehavior) {
            this.consultarClienteExAsync(obj, toStringBehavior, null);
        }
        
        /// <remarks/>
        public void consultarClienteExAsync(Cliente obj, int toStringBehavior, object userState) {
            if ((this.consultarClienteExOperationCompleted == null)) {
                this.consultarClienteExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarClienteExOperationCompleted);
            }
            this.InvokeAsync("consultarClienteEx", new object[] {
                        obj,
                        toStringBehavior}, this.consultarClienteExOperationCompleted, userState);
        }
        
        private void OnconsultarClienteExOperationCompleted(object arg) {
            if ((this.consultarClienteExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarClienteExCompleted(this, new consultarClienteExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/salvarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void salvarCliente(Cliente obj) {
            this.Invoke("salvarCliente", new object[] {
                        obj});
        }
        
        /// <remarks/>
        public void salvarClienteAsync(Cliente obj) {
            this.salvarClienteAsync(obj, null);
        }
        
        /// <remarks/>
        public void salvarClienteAsync(Cliente obj, object userState) {
            if ((this.salvarClienteOperationCompleted == null)) {
                this.salvarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsalvarClienteOperationCompleted);
            }
            this.InvokeAsync("salvarCliente", new object[] {
                        obj}, this.salvarClienteOperationCompleted, userState);
        }
        
        private void OnsalvarClienteOperationCompleted(object arg) {
            if ((this.salvarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.salvarClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/excluirCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void excluirCliente(Cliente obj) {
            this.Invoke("excluirCliente", new object[] {
                        obj});
        }
        
        /// <remarks/>
        public void excluirClienteAsync(Cliente obj) {
            this.excluirClienteAsync(obj, null);
        }
        
        /// <remarks/>
        public void excluirClienteAsync(Cliente obj, object userState) {
            if ((this.excluirClienteOperationCompleted == null)) {
                this.excluirClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexcluirClienteOperationCompleted);
            }
            this.InvokeAsync("excluirCliente", new object[] {
                        obj}, this.excluirClienteOperationCompleted, userState);
        }
        
        private void OnexcluirClienteOperationCompleted(object arg) {
            if ((this.excluirClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.excluirClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pegarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente pegarCliente(int codigo) {
            object[] results = this.Invoke("pegarCliente", new object[] {
                        codigo});
            return ((Cliente)(results[0]));
        }
        
        /// <remarks/>
        public void pegarClienteAsync(int codigo) {
            this.pegarClienteAsync(codigo, null);
        }
        
        /// <remarks/>
        public void pegarClienteAsync(int codigo, object userState) {
            if ((this.pegarClienteOperationCompleted == null)) {
                this.pegarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpegarClienteOperationCompleted);
            }
            this.InvokeAsync("pegarCliente", new object[] {
                        codigo}, this.pegarClienteOperationCompleted, userState);
        }
        
        private void OnpegarClienteOperationCompleted(object arg) {
            if ((this.pegarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pegarClienteCompleted(this, new pegarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pegarClienteEx", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente pegarClienteEx(int codigo, int toStringBehavior) {
            object[] results = this.Invoke("pegarClienteEx", new object[] {
                        codigo,
                        toStringBehavior});
            return ((Cliente)(results[0]));
        }
        
        /// <remarks/>
        public void pegarClienteExAsync(int codigo, int toStringBehavior) {
            this.pegarClienteExAsync(codigo, toStringBehavior, null);
        }
        
        /// <remarks/>
        public void pegarClienteExAsync(int codigo, int toStringBehavior, object userState) {
            if ((this.pegarClienteExOperationCompleted == null)) {
                this.pegarClienteExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpegarClienteExOperationCompleted);
            }
            this.InvokeAsync("pegarClienteEx", new object[] {
                        codigo,
                        toStringBehavior}, this.pegarClienteExOperationCompleted, userState);
        }
        
        private void OnpegarClienteExOperationCompleted(object arg) {
            if ((this.pegarClienteExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pegarClienteExCompleted(this, new pegarClienteExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Exercicio {
        
        private int codigoField;
        
        private string descricaoField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cliente {
        
        private int codigoField;
        
        private string nomeField;
        
        private string cpfField;
        
        private string rgField;
        
        private System.DateTime dataNascField;
        
        private string logradouroField;
        
        private string numLogField;
        
        private string complementoField;
        
        private string bairroField;
        
        private string cidadeField;
        
        private string ufField;
        
        private string cepField;
        
        private string estCivilField;
        
        private string sexoField;
        
        private string telefoneField;
        
        private string celularField;
        
        private string emailField;
        
        private System.DateTime valExameMedicoField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        public string Rg {
            get {
                return this.rgField;
            }
            set {
                this.rgField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataNasc {
            get {
                return this.dataNascField;
            }
            set {
                this.dataNascField = value;
            }
        }
        
        /// <remarks/>
        public string Logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        public string NumLog {
            get {
                return this.numLogField;
            }
            set {
                this.numLogField = value;
            }
        }
        
        /// <remarks/>
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        public string Cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        public string EstCivil {
            get {
                return this.estCivilField;
            }
            set {
                this.estCivilField = value;
            }
        }
        
        /// <remarks/>
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        public string Celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ValExameMedico {
            get {
                return this.valExameMedicoField;
            }
            set {
                this.valExameMedicoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Objetivo {
        
        private int codigoField;
        
        private string descricaoField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getLastMsgErrorCompletedEventHandler(object sender, getLastMsgErrorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLastMsgErrorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLastMsgErrorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void salvarTesteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void consultarExercicioCompletedEventHandler(object sender, consultarExercicioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarExercicioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarExercicioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Exercicio[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Exercicio[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void consultarExercicioExCompletedEventHandler(object sender, consultarExercicioExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarExercicioExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarExercicioExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Exercicio[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Exercicio[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void salvarExercicioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void excluirExercicioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void pegarExercicioCompletedEventHandler(object sender, pegarExercicioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pegarExercicioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pegarExercicioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Exercicio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Exercicio)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void pegarExercicioExCompletedEventHandler(object sender, pegarExercicioExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pegarExercicioExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pegarExercicioExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Exercicio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Exercicio)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void consultarObjetivoCompletedEventHandler(object sender, consultarObjetivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarObjetivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarObjetivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Objetivo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Objetivo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void consultarObjetivoExCompletedEventHandler(object sender, consultarObjetivoExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarObjetivoExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarObjetivoExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Objetivo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Objetivo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void salvarObjetivoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void excluirObjetivoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void pegarObjetivoCompletedEventHandler(object sender, pegarObjetivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pegarObjetivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pegarObjetivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Objetivo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Objetivo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void pegarObjetivoExCompletedEventHandler(object sender, pegarObjetivoExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pegarObjetivoExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pegarObjetivoExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Objetivo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Objetivo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void consultarClienteCompletedEventHandler(object sender, consultarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void consultarClienteExCompletedEventHandler(object sender, consultarClienteExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarClienteExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarClienteExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void salvarClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void excluirClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void pegarClienteCompletedEventHandler(object sender, pegarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pegarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pegarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void pegarClienteExCompletedEventHandler(object sender, pegarClienteExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pegarClienteExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pegarClienteExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591