//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18034.
// 
#pragma warning disable 1591

namespace FACliente.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLastMsgErrorOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarExercicioOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarExercicioExOperationCompleted;
        
        private System.Threading.SendOrPostCallback salvarExercicioOperationCompleted;
        
        private System.Threading.SendOrPostCallback excluirExercicioOperationCompleted;
        
        private System.Threading.SendOrPostCallback pegarExercicioOperationCompleted;
        
        private System.Threading.SendOrPostCallback pegarExercicioExOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarObjetivoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::FACliente.Properties.Settings.Default.FACliente_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event getLastMsgErrorCompletedEventHandler getLastMsgErrorCompleted;
        
        /// <remarks/>
        public event consultarExercicioCompletedEventHandler consultarExercicioCompleted;
        
        /// <remarks/>
        public event consultarExercicioExCompletedEventHandler consultarExercicioExCompleted;
        
        /// <remarks/>
        public event salvarExercicioCompletedEventHandler salvarExercicioCompleted;
        
        /// <remarks/>
        public event excluirExercicioCompletedEventHandler excluirExercicioCompleted;
        
        /// <remarks/>
        public event pegarExercicioCompletedEventHandler pegarExercicioCompleted;
        
        /// <remarks/>
        public event pegarExercicioExCompletedEventHandler pegarExercicioExCompleted;
        
        /// <remarks/>
        public event consultarObjetivoCompletedEventHandler consultarObjetivoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLastMsgError", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getLastMsgError() {
            object[] results = this.Invoke("getLastMsgError", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getLastMsgErrorAsync() {
            this.getLastMsgErrorAsync(null);
        }
        
        /// <remarks/>
        public void getLastMsgErrorAsync(object userState) {
            if ((this.getLastMsgErrorOperationCompleted == null)) {
                this.getLastMsgErrorOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLastMsgErrorOperationCompleted);
            }
            this.InvokeAsync("getLastMsgError", new object[0], this.getLastMsgErrorOperationCompleted, userState);
        }
        
        private void OngetLastMsgErrorOperationCompleted(object arg) {
            if ((this.getLastMsgErrorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLastMsgErrorCompleted(this, new getLastMsgErrorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultarExercicio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Exercicio[] consultarExercicio(Exercicio exer) {
            object[] results = this.Invoke("consultarExercicio", new object[] {
                        exer});
            return ((Exercicio[])(results[0]));
        }
        
        /// <remarks/>
        public void consultarExercicioAsync(Exercicio exer) {
            this.consultarExercicioAsync(exer, null);
        }
        
        /// <remarks/>
        public void consultarExercicioAsync(Exercicio exer, object userState) {
            if ((this.consultarExercicioOperationCompleted == null)) {
                this.consultarExercicioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarExercicioOperationCompleted);
            }
            this.InvokeAsync("consultarExercicio", new object[] {
                        exer}, this.consultarExercicioOperationCompleted, userState);
        }
        
        private void OnconsultarExercicioOperationCompleted(object arg) {
            if ((this.consultarExercicioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarExercicioCompleted(this, new consultarExercicioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultarExercicioEx", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Exercicio[] consultarExercicioEx(Exercicio exer, int toStringBehavior) {
            object[] results = this.Invoke("consultarExercicioEx", new object[] {
                        exer,
                        toStringBehavior});
            return ((Exercicio[])(results[0]));
        }
        
        /// <remarks/>
        public void consultarExercicioExAsync(Exercicio exer, int toStringBehavior) {
            this.consultarExercicioExAsync(exer, toStringBehavior, null);
        }
        
        /// <remarks/>
        public void consultarExercicioExAsync(Exercicio exer, int toStringBehavior, object userState) {
            if ((this.consultarExercicioExOperationCompleted == null)) {
                this.consultarExercicioExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarExercicioExOperationCompleted);
            }
            this.InvokeAsync("consultarExercicioEx", new object[] {
                        exer,
                        toStringBehavior}, this.consultarExercicioExOperationCompleted, userState);
        }
        
        private void OnconsultarExercicioExOperationCompleted(object arg) {
            if ((this.consultarExercicioExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarExercicioExCompleted(this, new consultarExercicioExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/salvarExercicio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void salvarExercicio(Exercicio exer) {
            this.Invoke("salvarExercicio", new object[] {
                        exer});
        }
        
        /// <remarks/>
        public void salvarExercicioAsync(Exercicio exer) {
            this.salvarExercicioAsync(exer, null);
        }
        
        /// <remarks/>
        public void salvarExercicioAsync(Exercicio exer, object userState) {
            if ((this.salvarExercicioOperationCompleted == null)) {
                this.salvarExercicioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsalvarExercicioOperationCompleted);
            }
            this.InvokeAsync("salvarExercicio", new object[] {
                        exer}, this.salvarExercicioOperationCompleted, userState);
        }
        
        private void OnsalvarExercicioOperationCompleted(object arg) {
            if ((this.salvarExercicioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.salvarExercicioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/excluirExercicio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void excluirExercicio(Exercicio exer) {
            this.Invoke("excluirExercicio", new object[] {
                        exer});
        }
        
        /// <remarks/>
        public void excluirExercicioAsync(Exercicio exer) {
            this.excluirExercicioAsync(exer, null);
        }
        
        /// <remarks/>
        public void excluirExercicioAsync(Exercicio exer, object userState) {
            if ((this.excluirExercicioOperationCompleted == null)) {
                this.excluirExercicioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexcluirExercicioOperationCompleted);
            }
            this.InvokeAsync("excluirExercicio", new object[] {
                        exer}, this.excluirExercicioOperationCompleted, userState);
        }
        
        private void OnexcluirExercicioOperationCompleted(object arg) {
            if ((this.excluirExercicioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.excluirExercicioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pegarExercicio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Exercicio pegarExercicio(int codigo) {
            object[] results = this.Invoke("pegarExercicio", new object[] {
                        codigo});
            return ((Exercicio)(results[0]));
        }
        
        /// <remarks/>
        public void pegarExercicioAsync(int codigo) {
            this.pegarExercicioAsync(codigo, null);
        }
        
        /// <remarks/>
        public void pegarExercicioAsync(int codigo, object userState) {
            if ((this.pegarExercicioOperationCompleted == null)) {
                this.pegarExercicioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpegarExercicioOperationCompleted);
            }
            this.InvokeAsync("pegarExercicio", new object[] {
                        codigo}, this.pegarExercicioOperationCompleted, userState);
        }
        
        private void OnpegarExercicioOperationCompleted(object arg) {
            if ((this.pegarExercicioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pegarExercicioCompleted(this, new pegarExercicioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pegarExercicioEx", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Exercicio pegarExercicioEx(int codigo, int toStringBehavior) {
            object[] results = this.Invoke("pegarExercicioEx", new object[] {
                        codigo,
                        toStringBehavior});
            return ((Exercicio)(results[0]));
        }
        
        /// <remarks/>
        public void pegarExercicioExAsync(int codigo, int toStringBehavior) {
            this.pegarExercicioExAsync(codigo, toStringBehavior, null);
        }
        
        /// <remarks/>
        public void pegarExercicioExAsync(int codigo, int toStringBehavior, object userState) {
            if ((this.pegarExercicioExOperationCompleted == null)) {
                this.pegarExercicioExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpegarExercicioExOperationCompleted);
            }
            this.InvokeAsync("pegarExercicioEx", new object[] {
                        codigo,
                        toStringBehavior}, this.pegarExercicioExOperationCompleted, userState);
        }
        
        private void OnpegarExercicioExOperationCompleted(object arg) {
            if ((this.pegarExercicioExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pegarExercicioExCompleted(this, new pegarExercicioExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultarObjetivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Objetivo consultarObjetivo(Objetivo obj) {
            object[] results = this.Invoke("consultarObjetivo", new object[] {
                        obj});
            return ((Objetivo)(results[0]));
        }
        
        /// <remarks/>
        public void consultarObjetivoAsync(Objetivo obj) {
            this.consultarObjetivoAsync(obj, null);
        }
        
        /// <remarks/>
        public void consultarObjetivoAsync(Objetivo obj, object userState) {
            if ((this.consultarObjetivoOperationCompleted == null)) {
                this.consultarObjetivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarObjetivoOperationCompleted);
            }
            this.InvokeAsync("consultarObjetivo", new object[] {
                        obj}, this.consultarObjetivoOperationCompleted, userState);
        }
        
        private void OnconsultarObjetivoOperationCompleted(object arg) {
            if ((this.consultarObjetivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarObjetivoCompleted(this, new consultarObjetivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Exercicio {
        
        private int codigoField;
        
        private string descricaoField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Objetivo {
        
        private int codigoField;
        
        private string descricaoField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getLastMsgErrorCompletedEventHandler(object sender, getLastMsgErrorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLastMsgErrorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLastMsgErrorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void consultarExercicioCompletedEventHandler(object sender, consultarExercicioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarExercicioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarExercicioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Exercicio[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Exercicio[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void consultarExercicioExCompletedEventHandler(object sender, consultarExercicioExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarExercicioExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarExercicioExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Exercicio[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Exercicio[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void salvarExercicioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void excluirExercicioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void pegarExercicioCompletedEventHandler(object sender, pegarExercicioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pegarExercicioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pegarExercicioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Exercicio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Exercicio)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void pegarExercicioExCompletedEventHandler(object sender, pegarExercicioExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pegarExercicioExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pegarExercicioExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Exercicio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Exercicio)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void consultarObjetivoCompletedEventHandler(object sender, consultarObjetivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarObjetivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarObjetivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Objetivo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Objetivo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591